apiVersion: v1
kind: Service
metadata:
  labels:
    app: customermanagementsystem
  name: customermanagementsystem
spec:
  ports:
  - protocol: TCP
    port: 8081
    nodePort: 30001
  type: NodePort
  selector:
    io.kompose.service: customermanagementsystem
